export EDITOR="nvim"
export BROWSER="zen-browser"
export MUSICPLAYER="spotify"
export TERMINAL="kitty"
export ARCH_CONFIG_DIR="${HOME}/.config/rybelika"
export WALLHAVEN_API_KEY="qtLIxlOdpS5mn95Lma3uh5dOGc2ReYVq"
