# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/
windowrule = opacity 0.90 0.90, match:class kitty
windowrule = opacity 0.80 0.80, match:class foot
windowrule = opacity 0.80 0.80, match:class com.mitchellh.ghostty
windowrule = opacity 0.80 0.80, match:class org.wezfurlong.wezterm
windowrule = opacity 0.90 0.90, match:class firefox
windowrule = opacity 0.90 0.90, match:class zen
windowrule = opacity 0.90 0.90, match:class Chromium
windowrule = opacity 0.90 0.90, match:class vesktop
windowrule = opacity 0.90 0.90, match:class discord
windowrule = opacity 0.80 0.80, match:class material_color_config.py
windowrule = opacity 0.90 0.90, match:class moe.launcher.sleepy-launcher
windowrule = opacity 0.90 0.90, match:class moe.launcher.an-anime-game-launcher
windowrule = opacity 0.90 0.90, match:class moe.launcher.the-honkers-railway-launcher
windowrule = opacity 0.90 0.90, match:class Code
windowrule = opacity 0.80 0.80, match:class Rofi
windowrule = opacity 0.70 0.70, match:class Spotify
windowrule = opacity 0.80 0.80, match:class com.mastermindzh.tidal-hifi
windowrule = opacity 0.70 0.70, match:class spotube
windowrule = opacity 0.90 0.90, match:class steam
windowrule = opacity 0.90 0.90, match:class lutris
windowrule = opacity 0.80 0.80, match:class org.kde.dolphin, center on
windowrule = opacity 0.80 0.80, match:class org.kde.dolphin, float on
windowrule = opacity 0.80 0.80, match:class org.gnome.Nautilus, center on
windowrule = opacity 0.80 0.80, match:class org.gnome.Nautilus, float on
windowrule = opacity 0.80 0.80, match:class thunar, center on
windowrule = opacity 0.80 0.80, match:class thunar, float on 
windowrule = opacity 0.80 0.80, match:class xdg-desktop-portal-gtk
windowrule = opacity 0.80 0.80, match:class pavucontrol-qt, center on
windowrule = opacity 0.80 0.80, match:class pavucontrol-qt, float on
windowrule = opacity 0.80 0.80, match:class nwg-look
windowrule = opacity 0.80 0.80, match:class qt5ct, center on
windowrule = opacity 0.80 0.80, match:class qt5ct, float on
windowrule = opacity 0.80 0.80, match:class qt6ct, center on
windowrule = opacity 0.80 0.80, match:class qt6ct, float on
windowrule = opacity 0.80 0.80, match:class kvantummanager, center on
windowrule = opacity 0.80 0.80, match:class kvantummanager, float on
windowrule = opacity 0.80 0.80, match:class blueman-manager, center on
windowrule = opacity 0.80 0.80, match:class blueman-manager, float on

windowrule = match:class material_color_config.py, center on
windowrule = match:class material_color_config.py, float on

windowrule = size 1000 800, match:class org.kde.dolphin
windowrule = size 1000 800, match:class org.gnome.Nautilus
windowrule = size 800 600, match:class thunar

windowrule = match:class mpv, fullscreen on

layerrule = match:namespace gtk-layer-shell, blur on
layerrule = match:namespace gtk-layer-shell, ignore_alpha a
